#!/usr/bin/env bash
#
# Self-contained demo for `pgrls verify --mode write` + `--probe`.
#
#   pgrls proves cross-tenant WRITE isolation over each policy's WITH CHECK,
#   and --probe confirms that proof against a LIVE database.
#
# Subcommands (the .tape drives setup/fix/teardown in hidden blocks):
#   setup     spin up a throwaway Postgres + seed a write-leaky policy
#   fix       bind the WITH CHECK to the caller's tenant (drop the OR)
#   teardown  remove the container
#   demo      run the whole thing end-to-end (for a human, no recorder)
#
# Requires: docker, psql, and a pgrls >= 0.39.0 on PATH (write-mode + --probe
# ship on main 0.39.0; PyPI is still 0.32.0 at time of writing).
set -euo pipefail

CONTAINER=pgrls-write-probe-demo
PORT=55450
URL="postgresql://postgres:postgres@localhost:${PORT}/postgres"
PGRLS="${PGRLS:-pgrls}"
FIX_SQL="ALTER POLICY docs_write ON docs WITH CHECK (tenant_id = current_setting('app.tenant', true)::uuid)"

setup() {
  docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
  docker run -d --name "$CONTAINER" -e POSTGRES_PASSWORD=postgres -p ${PORT}:5432 postgres:16-alpine >/dev/null
  for _ in $(seq 1 30); do docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1 && break; sleep 1; done
  psql "$URL" -q <<'SQL'
create table docs (
  id        bigint generated by default as identity primary key,
  tenant_id uuid    not null,
  is_public boolean not null default false,
  body      text
);
alter table docs enable row level security;
-- reads are correctly scoped to the caller's tenant ...
create policy docs_read on docs for select to public
  using (tenant_id = current_setting('app.tenant', true)::uuid);
-- ... but the WITH CHECK has an OR that lets a caller INSERT a row
-- stamped for ANOTHER tenant, as long as is_public is true.
create policy docs_write on docs for insert to public
  with check (tenant_id = current_setting('app.tenant', true)::uuid or is_public);
grant select, insert on docs to public;
SQL
}

fix() {
  echo "-- bind the write-check to the caller's tenant (drop the OR):"
  echo "${FIX_SQL};"
  psql "$URL" -q -c "$FIX_SQL"
}

teardown() { docker rm -f "$CONTAINER" >/dev/null 2>&1 || true; }

demo() {
  setup
  echo "$ pgrls verify --mode write";          DATABASE_URL="$URL" "$PGRLS" verify --mode write --schemas public || true
  echo; echo "$ pgrls verify --mode write --probe"; DATABASE_URL="$URL" "$PGRLS" verify --mode write --probe --schemas public || true
  echo; fix
  echo; echo "$ pgrls verify --mode write --probe"; DATABASE_URL="$URL" "$PGRLS" verify --mode write --probe --schemas public || true
  teardown
}

case "${1:-demo}" in
  setup) setup ;;
  fix) fix ;;
  teardown) teardown ;;
  demo) demo ;;
  *) echo "usage: $0 [setup|fix|teardown|demo]" >&2; exit 1 ;;
esac
